### ISSUE TITLE
completion block not executed

### ISSUE THREAD

**Issue by selvamsankaran** [uploadcare/uploadcare-ios#19]
I am using only Uploadcare/core  in  my project.  When trying to upload a local file from iPhone, i am getting the progress but after progress completes the completion block is not called. How to fix this?

**Comment by Rusik** [comment]
Hi @selvamsankaran , thank you for the report. Can you tell us a more details about this issue. Maybe you can send a sample code or project.

**Comment by selvamsankaran** [comment]
Hi,


See this code. I am not getting the response, but getting the progress 
Just pass a local file path to this method and verify.


-(void)uploadFileFromData:(NSString*)filePath andDelegate:(id)delegate
{
    
    [self setDelegate:delegate];
    
    NSLog(@"Path: %@", filePath);
    
    NSString *contentTypeOrNil=nil;
    // autodetect content-type if not specified
    if (!contentTypeOrNil) {
        
        NSString *fileExtension = [filePath pathExtension];
        
        CFStringRef fileUTI = UTTypeCreatePreferredIdentifierForTag(kUTTagClassFilenameExtension, (__bridge CFStringRef)fileExtension, NULL);
        
        contentTypeOrNil = (__bridge NSString *)UTTypeCopyPreferredTagWithClass(fileUTI, kUTTagClassMIMEType);
        
        CFRelease(fileUTI);
        
        if (!contentTypeOrNil)
            contentTypeOrNil = @"text/plain";
        
    }
    
    
    NSString *fileName=[[filePath lastPathComponent] stringByDeletingPathExtension];

    NSData *fileData = [[NSData alloc] initWithContentsOfFile:fileName];
    
    
    UCFileUploadRequest *request = [UCFileUploadRequest requestWithFileData:fileData fileName:fileName mimeType:contentTypeOrNil];
    
    if (request) NSLog(@"Local file upload request created: %@", request);
    
    [[UCClient defaultClient] performUCRequest:request progress:^(NSUInteger totalBytesSent, NSUInteger totalBytesExpectedToSend) {
        
        float progress = (float)totalBytesSent / (float)totalBytesExpectedToSend;
        NSLog(@"Progress: %f", progress);
        
    } completion:^(id response, NSError *error) {
        
        if (!error) {
           
            NSLog(@"Response: %@", response);
            
            //if (completion) completion(response[@"file" ]);
            
        } else {
            
            NSLog(@"Error: %@", error.localizedDescription);
        }
    }];
    

    
}


Thanks
Selvam Sankaran

**Comment by selvamsankaran** [comment]
Please update the following.

> On Jul 26, 2016, at 6:47 PM, selvam sankaran <selvam.sankaran@kissflow.net> wrote:
> 
> NSData *fileData = [[NSData alloc] initWithContentsOfFile:fileName];

with this.

> NSData *fileData = [[NSData alloc] initWithContentsOfFile:filePath];


Thanks
Selvam S

**Comment by Rusik** [comment]
@selvamsankaran what kind of file it was?

**Comment by selvamsankaran** [comment]
Hi

Will send you a entire iOS project soon

Thanks

**Comment by Rusik** [comment]
Ok, will wait for it to see what happening

**Comment by selvamsankaran** [comment]
Hi Rusik,

When I make a separate iOS project with UploadCare, its working fine. Problem with my current integration of Uploadcare. Conflicts with AFNetworking library. Fixed the issue by calling the Uploadcare APIs through AFNetworking. Thanks for your steps.

**Comment by Rusik** [comment]
Cool, nice to hear!

**Comment by rsedykh** [comment]
@selvamsankaran, hi! I just want to tell you that we've just released new [uploadcare-swift integration](https://github.com/uploadcare/uploadcare-swift/releases/tag/0.1.0-alpha). I hope you can check it out. Feedback is very welcome. If you have any feature requests or questions, shoot!
