### ISSUE TITLE
Support for upload big files

### ISSUE THREAD

**Issue by heyzooi** [uploadcare/uploadcare-ios#25]
The current implementation loads the data to be upload into memory, which makes impossible to upload big files.

**Comment by heyzooi** [comment]
I could fix the client, but to have an optimum solution I would need support for a few changes in the server side.

**Comment by msaintmartin** [comment]
Hi, i’m having trouble in handling video files around 300Mb, can this be the reason ?
Thanks

**Comment by dmitry-mukhin** [comment]
@msaintmartin if you're using this ios sdk, this is possible.

**Comment by msaintmartin** [comment]
Thanks for answering ! Any workaround to propose ? I'm creating an app that use video record and push as first feature.
Thanks

**Comment by dmitry-mukhin** [comment]
I'd propose to try to add a method of uploading files from FS, not memory.

**Comment by rsedykh** [comment]
Fixed in [uploadcare-swift](http://github.com/uploadcare/uploadcare-swift).
