### ISSUE TITLE
Проверка регистрации UCClient

### ISSUE THREAD

**Issue by lookforward-github** [uploadcare/uploadcare-ios#27]
Было бы очень удобно, если при попытке использования **UCClient** без регистрации **public key** модуль не крашил приложение, а выводил сообщение в дебаг терминал.

**Comment by rsedykh** [comment]
@lookforward-github привет! Лучше поздно, чем никогда. :-) Мы выпустили новую Swift-библиотеку, [0.1.0-alfa](https://github.com/uploadcare/uploadcare-swift/releases/tag/0.1.0-alpha). Учли ваш комментарий, больше ничего не крашится. Ошибки в консоли нет, но при любом запросе к API возвращается пользователю ошибка с текстом `pub_key is required`.
