### ISSUE TITLE
UIWebView is deprecated

### ISSUE THREAD

**Issue by yaamoo** [uploadcare/uploadcare-ios#31]
i'd want to submit my app in app store but i have an error that says:
"apple stop accepting submission of apps that uses UIWebView". the only part of my code that may use UIWebView is your sdk. please upgrade code with wkwebview

**Comment by dmitry-mukhin** [comment]
Thanks for the report,
this will be addressed in the next version.

**Comment by felixdkatt** [comment]
Any word on when that new version will be? This will block us from submitting to apple

**Comment by felixdkatt** [comment]
fix ---

`#import "UCWebViewController.h"
#import <WebKit/WebKit.h>
@interface UCWebViewController () <WKUIDelegate>
@property (nonatomic, copy) void (^cancelBlock)();
@property (nonatomic, strong) WKWebView *webView;
@property (nonatomic, strong) NSURL *url;
@end

@implementation UCWebViewController

- (id)initWithURL:(NSURL *)url cancelBlock:(void(^)())cancelBlock {
    self = [super init];
    if (self) {
        _url = url;
        _cancelBlock = cancelBlock;
    }
    return self;
}

- (void)viewDidLoad {
    [super viewDidLoad];
    self.webView = [[WKWebView alloc] init];
    [self.view addSubview:self.webView];
    
    NSDictionary *views = @{@"webView":self.webView};
    
    [self.webView setTranslatesAutoresizingMaskIntoConstraints:NO];
    
    NSArray *horizontal = [NSLayoutConstraint constraintsWithVisualFormat:@"H:|[webView]|" options:0 metrics:nil views:views];
    NSArray *vertical = [NSLayoutConstraint constraintsWithVisualFormat:@"V:|[webView]|" options:0 metrics:nil views:views];
    
    [self.view addConstraints:horizontal];
    [self.view addConstraints:vertical];
    
    [self.webView loadRequest:[NSURLRequest requestWithURL:self.url]];
    
    UIBarButtonItem *cancelButton = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemCancel target:self action:@selector(close)];
    self.navigationItem.rightBarButtonItem = cancelButton;
}

- (void)close {
    if (self.cancelBlock) self.cancelBlock();
    [self dismissViewControllerAnimated:YES completion:nil];
}

@end`

**Comment by felixdkatt** [comment]
i forked the fix here for anyone who wants it
https://github.com/felixdkatt/uploadcare-ios

**Comment by rsedykh** [comment]
Hey @felixdkatt, @yaamoo. We've just released new uploadcare-swift integration, [0.1.0-alfa](https://github.com/uploadcare/uploadcare-swift/releases/tag/0.1.0-alpha). I hope you can check it out. Feedback is very welcome. If you have any feature requests or questions, shoot!
