### ISSUE TITLE
AFNetworking Dependency Out of Date

### ISSUE THREAD

**Issue by ksylvest** [uploadcare/uploadcare-ios#9]
**1.2.0** is a few years old now and makes it very difficult to integrate with an existing project that uses the library. Any chance of upgrading to **2.5.1**?

https://github.com/AFNetworking/AFNetworking/wiki/AFNetworking-2.0-Migration-Guide

**Comment by dmitry-mukhin** [comment]
@ksylvest we will gladly accept your pull request if you have some time to fix that.
thanks!

**Comment by ksylvest** [comment]
@dmitry-mukhin This is kind of a corporate product that requires a subscription to use... Does your company not have resources to maintain this?

**Comment by dmitry-mukhin** [comment]
we are a humble startup, and our resources are quite limited :)

**Comment by Rusik** [comment]
@ksylvest Hi! We've updated our library to 3.0 version. Now it has no third-party dependecies and separated to two layers: Core and UI. Feel free to update it and submit issues if you'll find any.
